# Generated by Django 4.2 on 2025-12-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sentiment',
            new_name='predicted_sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='corrected_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
