# Generated by Django 4.2 on 2025-12-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0002_rename_sentiment_review_predicted_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='corrected_sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='predicted_sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20),
        ),
    ]
